[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = [
    "dotnet restore LocalServicesMarketplace.Api/LocalServicesMarketplace.Api.csproj",
    "dotnet publish LocalServicesMarketplace.Api/LocalServicesMarketplace.Api.csproj -c Release -o out"
]

[start]
cmd = "cd out && dotnet LocalServicesMarketplace.Api.dll"